# Generated by Django 4.1.1 on 2022-10-16 06:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("email", models.CharField(max_length=64)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
                ),
                ("message", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date created")),
            ],
        ),
    ]
