# Generated by Django 4.1.1 on 2022-10-11 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("email", models.CharField(max_length=64)),
                ("phone", models.CharField(max_length=32)),
                ("message", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
