# Generated by Django 4.1.1 on 2022-09-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.IntegerField()),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Regime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulations.category")),
                ("regime", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulations.regime")),
                (
                    "sub_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regulations.subcategory"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("order", models.IntegerField(unique=True)),
                ("note", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="regulations.paragraph"
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="regulations.regulation",
                    ),
                ),
            ],
        ),
    ]
