# Generated by Django 4.1.1 on 2022-09-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regime",
            name="identifier",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="regulations.category",
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="regulations.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="regime",
            name="name",
            field=models.CharField(default="DEFAULT NAME (UPDATE)", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regime",
            name="number_range_max",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regime",
            name="number_range_min",
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regulation",
            name="regime_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="identifier",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="regulation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="regulations.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="identifier",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddConstraint(
            model_name="paragraph",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("regulation__isnull", False), ("category__isnull", True), ("sub_category__isnull", True)),
                    models.Q(("regulation__isnull", True), ("category__isnull", False)),
                    _connector="OR",
                ),
                name="valid_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="regime",
            constraint=models.CheckConstraint(
                check=models.Q(("number_range_min__lt", models.F("number_range_max"))),
                name="number_range_min_less_than_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("regime_number__gte", models.F("regime__number_range_min")),
                    ("regime_number__lte", models.F("regime__number_range_max")),
                ),
                name="valid_regime_number",
            ),
        ),
    ]
