# Generated by Django 4.1.1 on 2022-11-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Opprettelsesdato"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Opprettelsesdato"),
        ),
        migrations.AlterField(
            model_name="regime",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Opprettelsesdato"),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Opprettelsesdato"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Opprettelsesdato"),
        ),
    ]
