# Generated by Django 4.1.1 on 2022-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="order",
            field=models.IntegerField(),
        ),
    ]
