# Generated by Django 4.1.1 on 2022-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regime",
            name="identifier",
            field=models.CharField(max_length=3),
        ),
    ]
