# Generated by Django 4.1.1 on 2022-09-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0002_alter_paragraph_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="label",
            field=models.TextField(null=True),
        ),
    ]
