# Generated by Django 4.1.1 on 2022-11-11 01:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("title_no", models.CharField(blank=True, max_length=256, null=True, verbose_name="title (Norwegian)")),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="description (English)"),
                ),
                (
                    "description_no",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="description (Norwegian)"),
                ),
                (
                    "page_content",
                    ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="page content (English)"),
                ),
                (
                    "page_content_no",
                    ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="page content (Norwegian)"),
                ),
                (
                    "sidebar_title",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="sidebar title (English)"),
                ),
                (
                    "sidebar_title_no",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="sidebar title (Norwegian)"),
                ),
                (
                    "sidebar_text",
                    ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="sidebar text (English)"),
                ),
                (
                    "sidebar_text_no",
                    ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="sidebar text (Norwegian)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="flatpages/images", verbose_name="sidebar image"
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
            bases=("flatpages.flatpage",),
        ),
    ]
