# Generated by Django 4.1.1 on 2022-10-31 14:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("title_description", models.CharField(blank=True, max_length=256, null=True)),
                ("page_content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="flatpages/images")),
                ("sidebar_title", models.CharField(blank=True, max_length=256, null=True)),
                ("sidebar_text", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("title_no", models.CharField(blank=True, max_length=256, null=True)),
                ("title_description_no", models.CharField(blank=True, max_length=256, null=True)),
                ("page_content_no", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("sidebar_title_no", models.CharField(blank=True, max_length=256, null=True)),
                ("sidebar_text_no", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            bases=("flatpages.flatpage",),
        ),
    ]
