# Generated by Django 4.1.1 on 2022-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_extendedflatpage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedflatpage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flatpages/images"),
        ),
    ]
