# Generated by Django 4.1.1 on 2022-10-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_extendedflatpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedflatpage",
            name="sidebar_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extendedflatpage",
            name="title_description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
