# Generated by Django 4.1.1 on 2022-10-24 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_extendedflatpage_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedflatpage",
            name="page_content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
