# Generated by Django 4.1.1 on 2022-10-27 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_extendedflatpage_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedflatpage",
            name="page_content_no",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extendedflatpage",
            name="sidebar_text_no",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extendedflatpage",
            name="title_description_no",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="extendedflatpage",
            name="sidebar_text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
