# Generated by Django 4.1.1 on 2022-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_extendedflatpage_page_content_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedflatpage",
            name="title_no",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
